# Google Cloud Platform Configuration
gcp:
  project_id: "porygon-pipelines"
  dataset_id: "walmart_training_tables"
  region: "us-east4"

# Training Configurations
training:
  training_table_name: "walmart_master_table"
  target_col: "tgt_monthly_sales_sum_3_next_months"
  benchmark_col: "tgt_benchmark"
  date_column: "ctx_date_month"
  id_columns: ["ctx_state_id", "ctx_store_id", "ctx_cat_id", "ctx_dept_id", "ctx_item_id"]
  outlier_threshold: .95
  training_start_date: "2011-02-01"
  train_end_date: "2014-12-01"
  val_start_date: "2015-04-01"
  val_end_date: "2016-01-01"


# Model Configuration
models:
  params: 
    xgboost:
      n_estimators: 100
      booster: "gbtree"
      tree_method: "hist"
      objective: "reg:quantileerror"
      quantile_alpha: .80
      early_stopping_rounds: 20
      random_state: 42
      