# Google Cloud Platform Configuration
gcp:
  project_id: "porygon-pipelines"
  dataset_id: "walmart_training_tables"
  region: "us-east4"

# Training Configurations
training:
  training_table_name: "master_table_ca2_itfeas"
  target_col: "tgt_monthly_sales_sum_3_next_months"
  potential_stockout_col: "tgt_days_is_zero_sales_lead_1_months"
  date_column: "ctx_date_month"
  id_columns: ["ctx_state_id", "ctx_store_id", "ctx_cat_id", "ctx_dept_id", "ctx_item_id"]
  train_val_split_date: "2015-01-01"
  # Load features from external file
  features_file: "features.yaml"

# Model Configuration
models:
  params: 
    xgboost:
      n_estimators: 100
      booster: "gbtree"
      tree_method: "hist"
      grow_policy: "lossguide"
      objective: "count:poisson"
      early_stopping_rounds: 20
      random_state: 42