# Google Cloud Platform Configuration
gcp:
  project_id: "porygon-pipelines"
  dataset_id: "m5_intermediate"
  region: "us-east4"

# Training Configurations
training:
  training_table_name: "training_table_v4"
  target_col: "tgt_total_sales"
  date_column: "date"
  id_column: "obs_id"
  train_val_split_date: "2015-04-01"
  # Load features from external file
  features_file: "features.yaml"

# Model Configuration
models:
  params: 
    xgboost:
      n_estimators: 200
      max_depth: 6
      learning_rate: 0.1
      min_child_weight: 1
      subsample: 0.8
      colsample_bytree: 0.8
      gamma: 0
      reg_alpha: 0
      reg_lambda: 1
      # objective: "reg:absoluteerror"
      early_stopping_rounds: 20
      random_state: 42
