# Google Cloud Platform Configuration
gcp:
  project_id: "porygon-pipelines"
  dataset_id: "thelook_featurestore"
  region: "us-east4"

# Training Configurations
training:
  training_table_name: main_demand_table
  target_col: "num_transactions"
  date_column: "date"
  id_column: "product_id"
  # Load features from external file
  features_file: "features.yaml"

# Model Configuration
models:
  params: 
    xgboost:
      n_estimators: 200
      max_depth: 6
      learning_rate: 0.1
      min_child_weight: 1
      subsample: 0.8
      colsample_bytree: 0.8
      gamma: 0
      reg_alpha: 0
      reg_lambda: 1
      early_stopping_rounds: 20
      random_state: 42
