# Feature list for model training
features:
- "fea_is_weekend"
- "fea_is_event_1"
- "fea_is_event_2"
- "fea_is_sporting_event"
- "fea_is_cultural_event"
- "fea_is_national_event"
- "fea_is_religious_event"
- "fea_is_snap_ca"
- "fea_is_snap_tx"
- "fea_is_snap_wi"
- "fea_month_sin"
- "fea_ca_monthly_sales_roll_avg_3_months"
- "fea_ca_monthly_sales_roll_std_3_months"
- "fea_ca_monthly_sales_roll_avg_6_months"
- "fea_ca_monthly_sales_roll_std_6_months"
- "fea_ca_monthly_sales_roll_avg_12_months"
- "fea_ca_monthly_sales_roll_std_12_months"
- "fea_tx_monthly_sales_roll_avg_3_months"
- "fea_tx_monthly_sales_roll_std_3_months"
- "fea_tx_monthly_sales_roll_avg_6_months"
- "fea_tx_monthly_sales_roll_std_6_months"
- "fea_tx_monthly_sales_roll_avg_12_months"
- "fea_tx_monthly_sales_roll_std_12_months"
- "fea_wi_monthly_sales_roll_avg_3_months"
- "fea_wi_monthly_sales_roll_std_3_months"
- "fea_wi_monthly_sales_roll_avg_6_months"
- "fea_wi_monthly_sales_roll_std_6_months"
- "fea_wi_monthly_sales_roll_avg_12_months"
- "fea_wi_monthly_sales_roll_std_12_months"
- "fea_hobbies_monthly_sales_roll_avg_3_months"
- "fea_hobbies_monthly_sales_roll_std_3_months"
- "fea_hobbies_monthly_sales_roll_avg_6_months"
- "fea_hobbies_monthly_sales_roll_std_6_months"
- "fea_hobbies_monthly_sales_roll_avg_12_months"
- "fea_hobbies_monthly_sales_roll_std_12_months"
- "fea_household_monthly_sales_roll_avg_3_months"
- "fea_household_monthly_sales_roll_std_3_months"
- "fea_household_monthly_sales_roll_avg_6_months"
- "fea_household_monthly_sales_roll_std_6_months"
- "fea_household_monthly_sales_roll_avg_12_months"
- "fea_household_monthly_sales_roll_std_12_months"
- "fea_foods_monthly_sales_roll_avg_3_months"
- "fea_foods_monthly_sales_roll_std_3_months"
- "fea_foods_monthly_sales_roll_avg_6_months"
- "fea_foods_monthly_sales_roll_std_6_months"
- "fea_foods_monthly_sales_roll_avg_12_months"
- "fea_foods_monthly_sales_roll_std_12_months"
- "fea_hobbies_1_monthly_sales_roll_avg_3_months"
- "fea_hobbies_1_monthly_sales_roll_std_3_months"
- "fea_hobbies_1_monthly_sales_roll_avg_6_months"
- "fea_hobbies_1_monthly_sales_roll_std_6_months"
- "fea_hobbies_1_monthly_sales_roll_avg_12_months"
- "fea_hobbies_1_monthly_sales_roll_std_12_months"
- "fea_hobbies_2_monthly_sales_roll_avg_3_months"
- "fea_hobbies_2_monthly_sales_roll_std_3_months"
- "fea_hobbies_2_monthly_sales_roll_avg_6_months"
- "fea_hobbies_2_monthly_sales_roll_std_6_months"
- "fea_hobbies_2_monthly_sales_roll_avg_12_months"
- "fea_hobbies_2_monthly_sales_roll_std_12_months"
- "fea_household_1_monthly_sales_roll_avg_3_months"
- "fea_household_1_monthly_sales_roll_std_3_months"
- "fea_household_1_monthly_sales_roll_avg_6_months"
- "fea_household_1_monthly_sales_roll_std_6_months"
- "fea_household_1_monthly_sales_roll_avg_12_months"
- "fea_household_1_monthly_sales_roll_std_12_months"
- "fea_household_2_monthly_sales_roll_avg_3_months"
- "fea_household_2_monthly_sales_roll_std_3_months"
- "fea_household_2_monthly_sales_roll_avg_6_months"
- "fea_household_2_monthly_sales_roll_std_6_months"
- "fea_household_2_monthly_sales_roll_avg_12_months"
- "fea_household_2_monthly_sales_roll_std_12_months"
- "fea_foods_1_monthly_sales_roll_avg_3_months"
- "fea_foods_1_monthly_sales_roll_std_3_months"
- "fea_foods_1_monthly_sales_roll_avg_6_months"
- "fea_foods_1_monthly_sales_roll_std_6_months"
- "fea_foods_1_monthly_sales_roll_avg_12_months"
- "fea_foods_1_monthly_sales_roll_std_12_months"
- "fea_foods_2_monthly_sales_roll_avg_3_months"
- "fea_foods_2_monthly_sales_roll_std_3_months"
- "fea_foods_2_monthly_sales_roll_avg_6_months"
- "fea_foods_2_monthly_sales_roll_std_6_months"
- "fea_foods_2_monthly_sales_roll_avg_12_months"
- "fea_foods_2_monthly_sales_roll_std_12_months"
- "fea_foods_3_monthly_sales_roll_avg_3_months"
- "fea_foods_3_monthly_sales_roll_std_3_months"
- "fea_foods_3_monthly_sales_roll_avg_6_months"
- "fea_foods_3_monthly_sales_roll_std_6_months"
- "fea_foods_3_monthly_sales_roll_avg_12_months"
- "fea_foods_3_monthly_sales_roll_std_12_months"
- "fea_ca_1_monthly_sales_roll_avg_3_months"
- "fea_ca_1_monthly_sales_roll_std_3_months"
- "fea_ca_1_monthly_sales_roll_avg_6_months"
- "fea_ca_1_monthly_sales_roll_std_6_months"
- "fea_ca_1_monthly_sales_roll_avg_12_months"
- "fea_ca_1_monthly_sales_roll_std_12_months"
- "fea_ca_2_monthly_sales_roll_avg_3_months"
- "fea_ca_2_monthly_sales_roll_std_3_months"
- "fea_ca_2_monthly_sales_roll_avg_6_months"
- "fea_ca_2_monthly_sales_roll_std_6_months"
- "fea_ca_2_monthly_sales_roll_avg_12_months"
- "fea_ca_2_monthly_sales_roll_std_12_months"
- "fea_ca_3_monthly_sales_roll_avg_3_months"
- "fea_ca_3_monthly_sales_roll_std_3_months"
- "fea_ca_3_monthly_sales_roll_avg_6_months"
- "fea_ca_3_monthly_sales_roll_std_6_months"
- "fea_ca_3_monthly_sales_roll_avg_12_months"
- "fea_ca_3_monthly_sales_roll_std_12_months"
- "fea_ca_4_monthly_sales_roll_avg_3_months"
- "fea_ca_4_monthly_sales_roll_std_3_months"
- "fea_ca_4_monthly_sales_roll_avg_6_months"
- "fea_ca_4_monthly_sales_roll_std_6_months"
- "fea_ca_4_monthly_sales_roll_avg_12_months"
- "fea_ca_4_monthly_sales_roll_std_12_months"
- "fea_tx_1_monthly_sales_roll_avg_3_months"
- "fea_tx_1_monthly_sales_roll_std_3_months"
- "fea_tx_1_monthly_sales_roll_avg_6_months"
- "fea_tx_1_monthly_sales_roll_std_6_months"
- "fea_tx_1_monthly_sales_roll_avg_12_months"
- "fea_tx_1_monthly_sales_roll_std_12_months"
- "fea_tx_2_monthly_sales_roll_avg_3_months"
- "fea_tx_2_monthly_sales_roll_std_3_months"
- "fea_tx_2_monthly_sales_roll_avg_6_months"
- "fea_tx_2_monthly_sales_roll_std_6_months"
- "fea_tx_2_monthly_sales_roll_avg_12_months"
- "fea_tx_2_monthly_sales_roll_std_12_months"
- "fea_tx_3_monthly_sales_roll_avg_3_months"
- "fea_tx_3_monthly_sales_roll_std_3_months"
- "fea_tx_3_monthly_sales_roll_avg_6_months"
- "fea_tx_3_monthly_sales_roll_std_6_months"
- "fea_tx_3_monthly_sales_roll_avg_12_months"
- "fea_tx_3_monthly_sales_roll_std_12_months"
- "fea_wi_1_monthly_sales_roll_avg_3_months"
- "fea_wi_1_monthly_sales_roll_std_3_months"
- "fea_wi_1_monthly_sales_roll_avg_6_months"
- "fea_wi_1_monthly_sales_roll_std_6_months"
- "fea_wi_1_monthly_sales_roll_avg_12_months"
- "fea_wi_1_monthly_sales_roll_std_12_months"
- "fea_wi_2_monthly_sales_roll_avg_3_months"
- "fea_wi_2_monthly_sales_roll_std_3_months"
- "fea_wi_2_monthly_sales_roll_avg_6_months"
- "fea_wi_2_monthly_sales_roll_std_6_months"
- "fea_wi_2_monthly_sales_roll_avg_12_months"
- "fea_wi_2_monthly_sales_roll_std_12_months"
- "fea_wi_3_monthly_sales_roll_avg_3_months"
- "fea_wi_3_monthly_sales_roll_std_3_months"
- "fea_wi_3_monthly_sales_roll_avg_6_months"
- "fea_wi_3_monthly_sales_roll_std_6_months"
- "fea_wi_3_monthly_sales_roll_avg_12_months"
- "fea_wi_3_monthly_sales_roll_std_12_months"
- "fea_item_price_avg"
- "fea_item_price_min"
- "fea_item_price_max"
- "fea_item_price_std"
- "fea_store_price_avg"
- "fea_store_price_min"
- "fea_store_price_max"
- "fea_store_price_std"
- "fea_store_unique_items"
- "fea_state_price_avg"
- "fea_state_price_min"
- "fea_state_price_max"
- "fea_state_price_std"
- "fea_dept_price_avg"
- "fea_dept_price_min"
- "fea_dept_price_max"
- "fea_dept_price_std"
- "fea_dept_unique_items"
- "fea_price_change_direction_1m"
- "fea_price_pct_change_1m"
- "fea_price_pct_change_3m"
- "fea_price_pct_change_6m"
- "fea_price_abs_change_1m"
- "fea_price_abs_change_3m"
- "fea_price_abs_change_6m"
- "fea_item_vs_store_price_ratio"
- "fea_item_vs_dept_price_ratio"
- "fea_item_vs_state_price_ratio"
- "fea_item_price_min_roll_avg_3_months"
- "fea_item_price_min_roll_std_3_months"
- "fea_item_price_min_roll_avg_6_months"
- "fea_item_price_min_roll_std_6_months"
- "fea_item_price_min_roll_avg_12_months"
- "fea_item_price_min_roll_std_12_months"
- "fea_item_price_max_roll_avg_3_months"
- "fea_item_price_max_roll_std_3_months"
- "fea_item_price_max_roll_avg_6_months"
- "fea_item_price_max_roll_std_6_months"
- "fea_item_price_max_roll_avg_12_months"
- "fea_item_price_max_roll_std_12_months"
- "fea_item_price_std_roll_avg_3_months"
- "fea_item_price_std_roll_std_3_months"
- "fea_item_price_std_roll_avg_6_months"
- "fea_item_price_std_roll_std_6_months"
- "fea_item_price_std_roll_avg_12_months"
- "fea_item_price_std_roll_std_12_months"
- "fea_item_price_avg_roll_avg_3_months"
- "fea_item_price_avg_roll_std_3_months"
- "fea_item_price_avg_roll_avg_6_months"
- "fea_item_price_avg_roll_std_6_months"
- "fea_item_price_avg_roll_avg_12_months"
- "fea_item_price_avg_roll_std_12_months"
- "fea_item_store_price_min_roll_avg_3_months"
- "fea_item_store_price_min_roll_std_3_months"
- "fea_item_store_price_min_roll_avg_6_months"
- "fea_item_store_price_min_roll_std_6_months"
- "fea_item_store_price_min_roll_avg_12_months"
- "fea_item_store_price_min_roll_std_12_months"
- "fea_item_store_price_max_roll_avg_3_months"
- "fea_item_store_price_max_roll_std_3_months"
- "fea_item_store_price_max_roll_avg_6_months"
- "fea_item_store_price_max_roll_std_6_months"
- "fea_item_store_price_max_roll_avg_12_months"
- "fea_item_store_price_max_roll_std_12_months"
- "fea_item_store_price_std_roll_avg_3_months"
- "fea_item_store_price_std_roll_std_3_months"
- "fea_item_store_price_std_roll_avg_6_months"
- "fea_item_store_price_std_roll_std_6_months"
- "fea_item_store_price_std_roll_avg_12_months"
- "fea_item_store_price_std_roll_std_12_months"
- "fea_item_store_price_avg_roll_avg_3_months"
- "fea_item_store_price_avg_roll_std_3_months"
- "fea_item_store_price_avg_roll_avg_6_months"
- "fea_item_store_price_avg_roll_std_6_months"
- "fea_item_store_price_avg_roll_avg_12_months"
- "fea_item_store_price_avg_roll_std_12_months"
- "fea_store_price_avg_roll_avg_3_months"
- "fea_store_price_avg_roll_std_3_months"
- "fea_store_price_avg_roll_avg_6_months"
- "fea_store_price_avg_roll_std_6_months"
- "fea_store_price_avg_roll_avg_12_months"
- "fea_store_price_avg_roll_std_12_months"
- "fea_store_price_std_roll_avg_3_months"
- "fea_store_price_std_roll_std_3_months"
- "fea_store_price_std_roll_avg_6_months"
- "fea_store_price_std_roll_std_6_months"
- "fea_store_price_std_roll_avg_12_months"
- "fea_store_price_std_roll_std_12_months"
- "fea_store_unique_items_roll_avg_3_months"
- "fea_store_unique_items_roll_std_3_months"
- "fea_store_unique_items_roll_avg_6_months"
- "fea_store_unique_items_roll_std_6_months"
- "fea_store_unique_items_roll_avg_12_months"
- "fea_store_unique_items_roll_std_12_months"
- "fea_dept_price_avg_roll_avg_3_months"
- "fea_dept_price_avg_roll_std_3_months"
- "fea_dept_price_avg_roll_avg_6_months"
- "fea_dept_price_avg_roll_std_6_months"
- "fea_dept_price_avg_roll_avg_12_months"
- "fea_dept_price_avg_roll_std_12_months"
- "fea_dept_price_std_roll_avg_3_months"
- "fea_dept_price_std_roll_std_3_months"
- "fea_dept_price_std_roll_avg_6_months"
- "fea_dept_price_std_roll_std_6_months"
- "fea_dept_price_std_roll_avg_12_months"
- "fea_dept_price_std_roll_std_12_months"
- "fea_dept_price_min_roll_avg_3_months"
- "fea_dept_price_min_roll_std_3_months"
- "fea_dept_price_min_roll_avg_6_months"
- "fea_dept_price_min_roll_std_6_months"
- "fea_dept_price_min_roll_avg_12_months"
- "fea_dept_price_min_roll_std_12_months"
- "fea_dept_price_max_roll_avg_3_months"
- "fea_dept_price_max_roll_std_3_months"
- "fea_dept_price_max_roll_avg_6_months"
- "fea_dept_price_max_roll_std_6_months"
- "fea_dept_price_max_roll_avg_12_months"
- "fea_dept_price_max_roll_std_12_months"
- "fea_dept_unique_items_roll_avg_3_months"
- "fea_dept_unique_items_roll_std_3_months"
- "fea_dept_unique_items_roll_avg_6_months"
- "fea_dept_unique_items_roll_std_6_months"
- "fea_dept_unique_items_roll_avg_12_months"
- "fea_dept_unique_items_roll_std_12_months"
- "fea_state_price_avg_roll_avg_3_months"
- "fea_state_price_avg_roll_std_3_months"
- "fea_state_price_avg_roll_avg_6_months"
- "fea_state_price_avg_roll_std_6_months"
- "fea_state_price_avg_roll_avg_12_months"
- "fea_state_price_avg_roll_std_12_months"
- "fea_state_price_std_roll_avg_3_months"
- "fea_state_price_std_roll_std_3_months"
- "fea_state_price_std_roll_avg_6_months"
- "fea_state_price_std_roll_std_6_months"
- "fea_state_price_std_roll_avg_12_months"
- "fea_state_price_std_roll_std_12_months"
- "fea_item_vs_store_price_ratio_roll_avg_3_months"
- "fea_item_vs_store_price_ratio_roll_std_3_months"
- "fea_item_vs_store_price_ratio_roll_avg_6_months"
- "fea_item_vs_store_price_ratio_roll_std_6_months"
- "fea_item_vs_store_price_ratio_roll_avg_12_months"
- "fea_item_vs_store_price_ratio_roll_std_12_months"
- "fea_item_vs_dept_price_ratio_roll_avg_3_months"
- "fea_item_vs_dept_price_ratio_roll_std_3_months"
- "fea_item_vs_dept_price_ratio_roll_avg_6_months"
- "fea_item_vs_dept_price_ratio_roll_std_6_months"
- "fea_item_vs_dept_price_ratio_roll_avg_12_months"
- "fea_item_vs_dept_price_ratio_roll_std_12_months"
- "fea_item_vs_state_price_ratio_roll_avg_3_months"
- "fea_item_vs_state_price_ratio_roll_std_3_months"
- "fea_item_vs_state_price_ratio_roll_avg_6_months"
- "fea_item_vs_state_price_ratio_roll_std_6_months"
- "fea_item_vs_state_price_ratio_roll_avg_12_months"
- "fea_item_vs_state_price_ratio_roll_std_12_months"
- "fea_item_monthly_sales"
- "fea_num_days_item_is_zero_sales"
- "fea_item_monthly_sales_roll_avg_3_months"
- "fea_item_monthly_sales_roll_avg_6_months"
- "fea_item_monthly_sales_roll_avg_12_months"
- "fea_item_monthly_sales_roll_std_3_months"
- "fea_item_monthly_sales_roll_std_6_months"
- "fea_item_monthly_sales_roll_std_12_months"
- "fea_item_monthly_sales_lag_1_months"
- "fea_item_monthly_sales_lag_2_months"
- "fea_item_monthly_sales_lag_3_months"
- "fea_item_monthly_sales_lag_4_months"
- "fea_num_days_item_is_zero_sales_roll_avg_3_months"
- "fea_num_days_item_is_zero_sales_roll_avg_6_months"
- "fea_num_days_item_is_zero_sales_roll_avg_12_months"
- "fea_num_days_item_is_zero_sales_roll_std_3_months"
- "fea_num_days_item_is_zero_sales_roll_std_6_months"
- "fea_num_days_item_is_zero_sales_roll_std_12_months"
- "fea_num_days_item_is_zero_sales_lag_1_months"
- "fea_num_days_item_is_zero_sales_lag_2_months"
- "fea_num_days_item_is_zero_sales_lag_3_months"
- "fea_num_days_item_is_zero_sales_lag_4_months"
- "fea_state_item_monthly_sales"
- "fea_state_item_num_days_is_zero_sales"
- "fea_state_item_monthly_sales_roll_avg_3_months"
- "fea_state_item_monthly_sales_roll_avg_6_months"
- "fea_state_item_monthly_sales_roll_avg_12_months"
- "fea_state_item_monthly_sales_roll_std_3_months"
- "fea_state_item_monthly_sales_roll_std_6_months"
- "fea_state_item_monthly_sales_roll_std_12_months"
- "fea_state_item_num_days_is_zero_sales_roll_avg_3_months"
- "fea_state_item_num_days_is_zero_sales_roll_avg_6_months"
- "fea_state_item_num_days_is_zero_sales_roll_avg_12_months"
- "fea_state_item_num_days_is_zero_sales_roll_std_3_months"
- "fea_state_item_num_days_is_zero_sales_roll_std_6_months"
- "fea_state_item_num_days_is_zero_sales_roll_std_12_months"
- "fea_all_item_monthly_sales"
- "fea_all_item_num_days_is_zero_sales"
- "fea_all_item_monthly_sales_roll_avg_3_months"
- "fea_all_item_monthly_sales_roll_avg_6_months"
- "fea_all_item_monthly_sales_roll_avg_12_months"
- "fea_all_item_monthly_sales_roll_std_3_months"
- "fea_all_item_monthly_sales_roll_std_6_months"
- "fea_all_item_monthly_sales_roll_std_12_months"
- "fea_state_id_encoded"
- "fea_cat_id_encoded"
- "fea_dept_id_encoded"
- "fea_store_id_encoded"
- "fea_item_id_encoded"