# Feature list for model training
features:
- "fea_state_id_encoded"
- "fea_cat_id_encoded"
- "fea_dept_id_encoded"
- "fea_store_id_encoded"
- "fea_sales_roll_6"
- "fea_sales_roll_12"
- "fea_month_sin"
- "fea_is_snap_ca"
- "fea_is_snap_tx"
- "fea_is_snap_wi"
- "fea_is_weekend"
- "fea_is_event_1"
- "fea_is_event_2"
- "fea_is_sporting_event"
- "fea_is_cultural_event"
- "fea_is_national_event"
- "fea_is_religious_event"
- "fea_average_price_roll_6"
- "fea_average_price_roll_12"
- "fea_num_items_per_dept_per_store_roll_6"
- "fea_num_items_per_dept_per_store_roll_12"
- "fea_count_price_updates_roll_6"
- "fea_count_price_updates_roll_12"
- 'fea_mean_temprerature_roll_6'
- 'fea_mean_temprerature_roll_12' 
- 'fea_mean_dewp_roll_6'
- 'fea_mean_dewp_roll_12' 
- 'fea_mean_visib_roll_6'
- 'fea_mean_visib_roll_12' 
- 'fea_mean_wdsp_roll_6'
- 'fea_mean_wdsp_roll_12' 
- 'fea_mean_prcp_roll_6'
- 'fea_mean_prcp_roll_12' 
- 'fea_mean_sndp_roll_6'
- 'fea_mean_sndp_roll_12'
- 'fea_mean_tornado_funnel_cloud_roll_6'
- 'fea_mean_tornado_funnel_cloud_roll_12'
- 'fea_mean_thunder_roll_6'
- 'fea_mean_thunder_roll_12'
- 'fea_mean_snow_ice_pellets_roll_6'
- 'fea_mean_snow_ice_pellets_roll_12'
- 'fea_mean_rain_drizzle_roll_6'
- 'fea_mean_rain_drizzle_roll_12'
- 'fea_mean_fog_roll_6'
- 'fea_mean_fog_roll_12'

